//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace EAM.WebServices
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Password", Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    [XmlRootAttribute("Password", Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class Password
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [XmlTextAttribute()]
        public string Value { get; set; }
        
        [XmlAttributeAttribute("Type")]
        public XmlQualifiedName Type { get; set; }
        
        [XmlAnyAttributeAttribute()]
        public List<XmlAttribute> AnyAttribute { get; set; }
    }
}
