//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace EAM.WebServices
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("UsernameToken", Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext", AnonymousType=true)]
    [XmlRootAttribute("UsernameToken", Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class UsernameToken
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("Username")]
        public Username Username { get; set; }
        
        [XmlElementAttribute("Password")]
        public Password Password { get; set; }
        
        [XmlAttributeAttribute("Id")]
        public string Id { get; set; }
        
        [XmlAttributeAttribute("Tenant")]
        public string Tenant { get; set; }
        
        [XmlAttributeAttribute("ContainsTenant")]
        public string ContainsTenant { get; set; }
        
        [XmlAnyAttributeAttribute()]
        public List<XmlAttribute> AnyAttribute { get; set; }
    }
}
